// This file is auto-generated by @hey-api/openapi-ts

import type { Client, ClientMeta, Options as Options2, RequestResult, TDataShape } from './client';
import { client } from './client.gen';
import type { CreateRunRunsPostData, CreateRunRunsPostErrors, CreateRunRunsPostResponses, DownloadStepArtifactRunsRunIdStepsStepNoArtifactGetData, DownloadStepArtifactRunsRunIdStepsStepNoArtifactGetErrors, DownloadStepArtifactRunsRunIdStepsStepNoArtifactGetResponses, GetRunRunsRunIdGetData, GetRunRunsRunIdGetErrors, GetRunRunsRunIdGetResponses, GetStepRowsRunsRunIdStepsStepNoRowsGetData, GetStepRowsRunsRunIdStepsStepNoRowsGetErrors, GetStepRowsRunsRunIdStepsStepNoRowsGetResponses, HealthHealthGetData, HealthHealthGetResponses, ListRunsRunsGetData, ListRunsRunsGetResponses, SaveEditedStepRunsRunIdStepsStepNoEditedPutData, SaveEditedStepRunsRunIdStepsStepNoEditedPutErrors, SaveEditedStepRunsRunIdStepsStepNoEditedPutResponses, StartStepRunsRunIdStepsStepNoStartPostData, StartStepRunsRunIdStepsStepNoStartPostErrors, StartStepRunsRunIdStepsStepNoStartPostResponses, StreamEventsRunsRunIdEventsGetData, StreamEventsRunsRunIdEventsGetErrors, StreamEventsRunsRunIdEventsGetResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

/**
 * List Runs
 */
export const listRunsRunsGet = <ThrowOnError extends boolean = false>(options?: Options<ListRunsRunsGetData, ThrowOnError>): RequestResult<ListRunsRunsGetResponses, unknown, ThrowOnError> => (options?.client ?? client).get<ListRunsRunsGetResponses, unknown, ThrowOnError>({ url: '/runs', ...options });

/**
 * Create Run
 */
export const createRunRunsPost = <ThrowOnError extends boolean = false>(options: Options<CreateRunRunsPostData, ThrowOnError>): RequestResult<CreateRunRunsPostResponses, CreateRunRunsPostErrors, ThrowOnError> => (options.client ?? client).post<CreateRunRunsPostResponses, CreateRunRunsPostErrors, ThrowOnError>({
    url: '/runs',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Get Run
 */
export const getRunRunsRunIdGet = <ThrowOnError extends boolean = false>(options: Options<GetRunRunsRunIdGetData, ThrowOnError>): RequestResult<GetRunRunsRunIdGetResponses, GetRunRunsRunIdGetErrors, ThrowOnError> => (options.client ?? client).get<GetRunRunsRunIdGetResponses, GetRunRunsRunIdGetErrors, ThrowOnError>({ url: '/runs/{run_id}', ...options });

/**
 * Start Step
 */
export const startStepRunsRunIdStepsStepNoStartPost = <ThrowOnError extends boolean = false>(options: Options<StartStepRunsRunIdStepsStepNoStartPostData, ThrowOnError>): RequestResult<StartStepRunsRunIdStepsStepNoStartPostResponses, StartStepRunsRunIdStepsStepNoStartPostErrors, ThrowOnError> => (options.client ?? client).post<StartStepRunsRunIdStepsStepNoStartPostResponses, StartStepRunsRunIdStepsStepNoStartPostErrors, ThrowOnError>({ url: '/runs/{run_id}/steps/{step_no}/start', ...options });

/**
 * Download Step Artifact
 */
export const downloadStepArtifactRunsRunIdStepsStepNoArtifactGet = <ThrowOnError extends boolean = false>(options: Options<DownloadStepArtifactRunsRunIdStepsStepNoArtifactGetData, ThrowOnError>): RequestResult<DownloadStepArtifactRunsRunIdStepsStepNoArtifactGetResponses, DownloadStepArtifactRunsRunIdStepsStepNoArtifactGetErrors, ThrowOnError> => (options.client ?? client).get<DownloadStepArtifactRunsRunIdStepsStepNoArtifactGetResponses, DownloadStepArtifactRunsRunIdStepsStepNoArtifactGetErrors, ThrowOnError>({ url: '/runs/{run_id}/steps/{step_no}/artifact', ...options });

/**
 * Get Step Rows
 */
export const getStepRowsRunsRunIdStepsStepNoRowsGet = <ThrowOnError extends boolean = false>(options: Options<GetStepRowsRunsRunIdStepsStepNoRowsGetData, ThrowOnError>): RequestResult<GetStepRowsRunsRunIdStepsStepNoRowsGetResponses, GetStepRowsRunsRunIdStepsStepNoRowsGetErrors, ThrowOnError> => (options.client ?? client).get<GetStepRowsRunsRunIdStepsStepNoRowsGetResponses, GetStepRowsRunsRunIdStepsStepNoRowsGetErrors, ThrowOnError>({ url: '/runs/{run_id}/steps/{step_no}/rows', ...options });

/**
 * Save Edited Step
 */
export const saveEditedStepRunsRunIdStepsStepNoEditedPut = <ThrowOnError extends boolean = false>(options: Options<SaveEditedStepRunsRunIdStepsStepNoEditedPutData, ThrowOnError>): RequestResult<SaveEditedStepRunsRunIdStepsStepNoEditedPutResponses, SaveEditedStepRunsRunIdStepsStepNoEditedPutErrors, ThrowOnError> => (options.client ?? client).put<SaveEditedStepRunsRunIdStepsStepNoEditedPutResponses, SaveEditedStepRunsRunIdStepsStepNoEditedPutErrors, ThrowOnError>({
    url: '/runs/{run_id}/steps/{step_no}/edited',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Stream Events
 */
export const streamEventsRunsRunIdEventsGet = <ThrowOnError extends boolean = false>(options: Options<StreamEventsRunsRunIdEventsGetData, ThrowOnError>): RequestResult<StreamEventsRunsRunIdEventsGetResponses, StreamEventsRunsRunIdEventsGetErrors, ThrowOnError> => (options.client ?? client).get<StreamEventsRunsRunIdEventsGetResponses, StreamEventsRunsRunIdEventsGetErrors, ThrowOnError>({ url: '/runs/{run_id}/events', ...options });

/**
 * Health
 */
export const healthHealthGet = <ThrowOnError extends boolean = false>(options?: Options<HealthHealthGetData, ThrowOnError>): RequestResult<HealthHealthGetResponses, unknown, ThrowOnError> => (options?.client ?? client).get<HealthHealthGetResponses, unknown, ThrowOnError>({ url: '/health', ...options });
