// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://127.0.0.1:8000' | (string & {});
};

/**
 * CreateRunRequest
 */
export type CreateRunRequest = {
    /**
     * Params
     */
    params?: {
        [key: string]: unknown;
    };
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * RunDetail
 */
export type RunDetail = {
    run: RunRead;
    /**
     * Steps
     */
    steps: Array<StepRead>;
};

/**
 * RunRead
 */
export type RunRead = {
    /**
     * Id
     */
    id: string;
    /**
     * Status
     */
    status: string;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Params
     */
    params: {
        [key: string]: unknown;
    };
};

/**
 * SaveEditedStepRequest
 */
export type SaveEditedStepRequest = {
    /**
     * Rows
     */
    rows?: Array<{
        [key: string]: unknown;
    }> | null;
    /**
     * Columns
     */
    columns?: Array<string> | null;
    /**
     * Data
     */
    data?: {
        [key: string]: unknown;
    } | null;
};

/**
 * StartStepResponse
 */
export type StartStepResponse = {
    run: RunRead;
    step: StepRead;
};

/**
 * StepJsonRows
 */
export type StepJsonRows = {
    /**
     * Kind
     */
    kind: 'json';
    /**
     * Data
     */
    data: {
        [key: string]: unknown;
    };
};

/**
 * StepRead
 */
export type StepRead = {
    /**
     * Id
     */
    id: number;
    /**
     * Run Id
     */
    run_id: string;
    /**
     * Step No
     */
    step_no: number;
    /**
     * Name
     */
    name: string;
    /**
     * Status
     */
    status: string;
    /**
     * Artifact Path
     */
    artifact_path: string | null;
    /**
     * Edited Artifact Path
     */
    edited_artifact_path: string | null;
    /**
     * Started At
     */
    started_at: string | null;
    /**
     * Finished At
     */
    finished_at: string | null;
};

/**
 * StepTableRows
 */
export type StepTableRows = {
    /**
     * Kind
     */
    kind: 'table';
    /**
     * Columns
     */
    columns: Array<string>;
    /**
     * Rows
     */
    rows: Array<{
        [key: string]: string;
    }>;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

export type ListRunsRunsGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/runs';
};

export type ListRunsRunsGetResponses = {
    /**
     * Response List Runs Runs Get
     *
     * Successful Response
     */
    200: Array<RunRead>;
};

export type ListRunsRunsGetResponse = ListRunsRunsGetResponses[keyof ListRunsRunsGetResponses];

export type CreateRunRunsPostData = {
    body: CreateRunRequest;
    path?: never;
    query?: never;
    url: '/runs';
};

export type CreateRunRunsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateRunRunsPostError = CreateRunRunsPostErrors[keyof CreateRunRunsPostErrors];

export type CreateRunRunsPostResponses = {
    /**
     * Successful Response
     */
    200: RunRead;
};

export type CreateRunRunsPostResponse = CreateRunRunsPostResponses[keyof CreateRunRunsPostResponses];

export type GetRunRunsRunIdGetData = {
    body?: never;
    path: {
        /**
         * Run Id
         */
        run_id: string;
    };
    query?: never;
    url: '/runs/{run_id}';
};

export type GetRunRunsRunIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetRunRunsRunIdGetError = GetRunRunsRunIdGetErrors[keyof GetRunRunsRunIdGetErrors];

export type GetRunRunsRunIdGetResponses = {
    /**
     * Successful Response
     */
    200: RunDetail;
};

export type GetRunRunsRunIdGetResponse = GetRunRunsRunIdGetResponses[keyof GetRunRunsRunIdGetResponses];

export type StartStepRunsRunIdStepsStepNoStartPostData = {
    body?: never;
    path: {
        /**
         * Run Id
         */
        run_id: string;
        /**
         * Step No
         */
        step_no: number;
    };
    query?: never;
    url: '/runs/{run_id}/steps/{step_no}/start';
};

export type StartStepRunsRunIdStepsStepNoStartPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type StartStepRunsRunIdStepsStepNoStartPostError = StartStepRunsRunIdStepsStepNoStartPostErrors[keyof StartStepRunsRunIdStepsStepNoStartPostErrors];

export type StartStepRunsRunIdStepsStepNoStartPostResponses = {
    /**
     * Successful Response
     */
    200: StartStepResponse;
};

export type StartStepRunsRunIdStepsStepNoStartPostResponse = StartStepRunsRunIdStepsStepNoStartPostResponses[keyof StartStepRunsRunIdStepsStepNoStartPostResponses];

export type DownloadStepArtifactRunsRunIdStepsStepNoArtifactGetData = {
    body?: never;
    path: {
        /**
         * Run Id
         */
        run_id: string;
        /**
         * Step No
         */
        step_no: number;
    };
    query?: never;
    url: '/runs/{run_id}/steps/{step_no}/artifact';
};

export type DownloadStepArtifactRunsRunIdStepsStepNoArtifactGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DownloadStepArtifactRunsRunIdStepsStepNoArtifactGetError = DownloadStepArtifactRunsRunIdStepsStepNoArtifactGetErrors[keyof DownloadStepArtifactRunsRunIdStepsStepNoArtifactGetErrors];

export type DownloadStepArtifactRunsRunIdStepsStepNoArtifactGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetStepRowsRunsRunIdStepsStepNoRowsGetData = {
    body?: never;
    path: {
        /**
         * Run Id
         */
        run_id: string;
        /**
         * Step No
         */
        step_no: number;
    };
    query?: {
        /**
         * Name
         */
        name?: string | null;
    };
    url: '/runs/{run_id}/steps/{step_no}/rows';
};

export type GetStepRowsRunsRunIdStepsStepNoRowsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetStepRowsRunsRunIdStepsStepNoRowsGetError = GetStepRowsRunsRunIdStepsStepNoRowsGetErrors[keyof GetStepRowsRunsRunIdStepsStepNoRowsGetErrors];

export type GetStepRowsRunsRunIdStepsStepNoRowsGetResponses = {
    /**
     * Response Get Step Rows Runs  Run Id  Steps  Step No  Rows Get
     *
     * Successful Response
     */
    200: StepTableRows | StepJsonRows;
};

export type GetStepRowsRunsRunIdStepsStepNoRowsGetResponse = GetStepRowsRunsRunIdStepsStepNoRowsGetResponses[keyof GetStepRowsRunsRunIdStepsStepNoRowsGetResponses];

export type SaveEditedStepRunsRunIdStepsStepNoEditedPutData = {
    body: SaveEditedStepRequest;
    path: {
        /**
         * Run Id
         */
        run_id: string;
        /**
         * Step No
         */
        step_no: number;
    };
    query?: never;
    url: '/runs/{run_id}/steps/{step_no}/edited';
};

export type SaveEditedStepRunsRunIdStepsStepNoEditedPutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SaveEditedStepRunsRunIdStepsStepNoEditedPutError = SaveEditedStepRunsRunIdStepsStepNoEditedPutErrors[keyof SaveEditedStepRunsRunIdStepsStepNoEditedPutErrors];

export type SaveEditedStepRunsRunIdStepsStepNoEditedPutResponses = {
    /**
     * Successful Response
     */
    200: StepRead;
};

export type SaveEditedStepRunsRunIdStepsStepNoEditedPutResponse = SaveEditedStepRunsRunIdStepsStepNoEditedPutResponses[keyof SaveEditedStepRunsRunIdStepsStepNoEditedPutResponses];

export type StreamEventsRunsRunIdEventsGetData = {
    body?: never;
    path: {
        /**
         * Run Id
         */
        run_id: string;
    };
    query?: never;
    url: '/runs/{run_id}/events';
};

export type StreamEventsRunsRunIdEventsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type StreamEventsRunsRunIdEventsGetError = StreamEventsRunsRunIdEventsGetErrors[keyof StreamEventsRunsRunIdEventsGetErrors];

export type StreamEventsRunsRunIdEventsGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type HealthHealthGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health';
};

export type HealthHealthGetResponses = {
    /**
     * Response Health Health Get
     *
     * Successful Response
     */
    200: {
        [key: string]: string;
    };
};

export type HealthHealthGetResponse = HealthHealthGetResponses[keyof HealthHealthGetResponses];
