// This file is auto-generated by @hey-api/openapi-ts

import type { Client, ClientMeta, Options as Options2, RequestResult, TDataShape } from './client';
import { client } from './client.gen';
import type { CreateRunRunsPostData, CreateRunRunsPostErrors, CreateRunRunsPostResponses, DownloadStepArtifactRunsRunIdStepsStepNoArtifactGetData, DownloadStepArtifactRunsRunIdStepsStepNoArtifactGetErrors, DownloadStepArtifactRunsRunIdStepsStepNoArtifactGetResponses, GetCodebookCodebooksDiseaseParameterGetData, GetCodebookCodebooksDiseaseParameterGetErrors, GetCodebookCodebooksDiseaseParameterGetResponses, GetRunRunsRunIdGetData, GetRunRunsRunIdGetErrors, GetRunRunsRunIdGetResponses, GetStagePromptPromptsStageGetData, GetStagePromptPromptsStageGetErrors, GetStagePromptPromptsStageGetResponses, GetStepIndexRunsRunIdStepsStepNoIndexGetData, GetStepIndexRunsRunIdStepsStepNoIndexGetErrors, GetStepIndexRunsRunIdStepsStepNoIndexGetResponses, GetStepRowsRunsRunIdStepsStepNoRowsGetData, GetStepRowsRunsRunIdStepsStepNoRowsGetErrors, GetStepRowsRunsRunIdStepsStepNoRowsGetResponses, HealthHealthGetData, HealthHealthGetResponses, ListRunEventsRunsRunIdEventsHistoryGetData, ListRunEventsRunsRunIdEventsHistoryGetErrors, ListRunEventsRunsRunIdEventsHistoryGetResponses, ListRunsRunsGetData, ListRunsRunsGetErrors, ListRunsRunsGetResponses, ReadLlmSettingsSettingsLlmGetData, ReadLlmSettingsSettingsLlmGetResponses, SaveEditedStepRunsRunIdStepsStepNoEditedPutData, SaveEditedStepRunsRunIdStepsStepNoEditedPutErrors, SaveEditedStepRunsRunIdStepsStepNoEditedPutResponses, StartStepRunsRunIdStepsStepNoStartPostData, StartStepRunsRunIdStepsStepNoStartPostErrors, StartStepRunsRunIdStepsStepNoStartPostResponses, StreamEventsRunsRunIdEventsGetData, StreamEventsRunsRunIdEventsGetErrors, StreamEventsRunsRunIdEventsGetResponses, UpdateLlmSettingsSettingsLlmPutData, UpdateLlmSettingsSettingsLlmPutErrors, UpdateLlmSettingsSettingsLlmPutResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

/**
 * List Runs
 */
export const listRunsRunsGet = <ThrowOnError extends boolean = false>(options?: Options<ListRunsRunsGetData, ThrowOnError>): RequestResult<ListRunsRunsGetResponses, ListRunsRunsGetErrors, ThrowOnError> => (options?.client ?? client).get<ListRunsRunsGetResponses, ListRunsRunsGetErrors, ThrowOnError>({ url: '/runs', ...options });

/**
 * Create Run
 */
export const createRunRunsPost = <ThrowOnError extends boolean = false>(options: Options<CreateRunRunsPostData, ThrowOnError>): RequestResult<CreateRunRunsPostResponses, CreateRunRunsPostErrors, ThrowOnError> => (options.client ?? client).post<CreateRunRunsPostResponses, CreateRunRunsPostErrors, ThrowOnError>({
    url: '/runs',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Get Run
 */
export const getRunRunsRunIdGet = <ThrowOnError extends boolean = false>(options: Options<GetRunRunsRunIdGetData, ThrowOnError>): RequestResult<GetRunRunsRunIdGetResponses, GetRunRunsRunIdGetErrors, ThrowOnError> => (options.client ?? client).get<GetRunRunsRunIdGetResponses, GetRunRunsRunIdGetErrors, ThrowOnError>({ url: '/runs/{run_id}', ...options });

/**
 * Start Step
 */
export const startStepRunsRunIdStepsStepNoStartPost = <ThrowOnError extends boolean = false>(options: Options<StartStepRunsRunIdStepsStepNoStartPostData, ThrowOnError>): RequestResult<StartStepRunsRunIdStepsStepNoStartPostResponses, StartStepRunsRunIdStepsStepNoStartPostErrors, ThrowOnError> => (options.client ?? client).post<StartStepRunsRunIdStepsStepNoStartPostResponses, StartStepRunsRunIdStepsStepNoStartPostErrors, ThrowOnError>({
    url: '/runs/{run_id}/steps/{step_no}/start',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Download Step Artifact
 */
export const downloadStepArtifactRunsRunIdStepsStepNoArtifactGet = <ThrowOnError extends boolean = false>(options: Options<DownloadStepArtifactRunsRunIdStepsStepNoArtifactGetData, ThrowOnError>): RequestResult<DownloadStepArtifactRunsRunIdStepsStepNoArtifactGetResponses, DownloadStepArtifactRunsRunIdStepsStepNoArtifactGetErrors, ThrowOnError> => (options.client ?? client).get<DownloadStepArtifactRunsRunIdStepsStepNoArtifactGetResponses, DownloadStepArtifactRunsRunIdStepsStepNoArtifactGetErrors, ThrowOnError>({ url: '/runs/{run_id}/steps/{step_no}/artifact', ...options });

/**
 * Get Step Rows
 */
export const getStepRowsRunsRunIdStepsStepNoRowsGet = <ThrowOnError extends boolean = false>(options: Options<GetStepRowsRunsRunIdStepsStepNoRowsGetData, ThrowOnError>): RequestResult<GetStepRowsRunsRunIdStepsStepNoRowsGetResponses, GetStepRowsRunsRunIdStepsStepNoRowsGetErrors, ThrowOnError> => (options.client ?? client).get<GetStepRowsRunsRunIdStepsStepNoRowsGetResponses, GetStepRowsRunsRunIdStepsStepNoRowsGetErrors, ThrowOnError>({ url: '/runs/{run_id}/steps/{step_no}/rows', ...options });

/**
 * Save Edited Step
 */
export const saveEditedStepRunsRunIdStepsStepNoEditedPut = <ThrowOnError extends boolean = false>(options: Options<SaveEditedStepRunsRunIdStepsStepNoEditedPutData, ThrowOnError>): RequestResult<SaveEditedStepRunsRunIdStepsStepNoEditedPutResponses, SaveEditedStepRunsRunIdStepsStepNoEditedPutErrors, ThrowOnError> => (options.client ?? client).put<SaveEditedStepRunsRunIdStepsStepNoEditedPutResponses, SaveEditedStepRunsRunIdStepsStepNoEditedPutErrors, ThrowOnError>({
    url: '/runs/{run_id}/steps/{step_no}/edited',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Stream Events
 */
export const streamEventsRunsRunIdEventsGet = <ThrowOnError extends boolean = false>(options: Options<StreamEventsRunsRunIdEventsGetData, ThrowOnError>): RequestResult<StreamEventsRunsRunIdEventsGetResponses, StreamEventsRunsRunIdEventsGetErrors, ThrowOnError> => (options.client ?? client).get<StreamEventsRunsRunIdEventsGetResponses, StreamEventsRunsRunIdEventsGetErrors, ThrowOnError>({ url: '/runs/{run_id}/events', ...options });

/**
 * List Run Events
 */
export const listRunEventsRunsRunIdEventsHistoryGet = <ThrowOnError extends boolean = false>(options: Options<ListRunEventsRunsRunIdEventsHistoryGetData, ThrowOnError>): RequestResult<ListRunEventsRunsRunIdEventsHistoryGetResponses, ListRunEventsRunsRunIdEventsHistoryGetErrors, ThrowOnError> => (options.client ?? client).get<ListRunEventsRunsRunIdEventsHistoryGetResponses, ListRunEventsRunsRunIdEventsHistoryGetErrors, ThrowOnError>({ url: '/runs/{run_id}/events/history', ...options });

/**
 * Get Codebook
 */
export const getCodebookCodebooksDiseaseParameterGet = <ThrowOnError extends boolean = false>(options: Options<GetCodebookCodebooksDiseaseParameterGetData, ThrowOnError>): RequestResult<GetCodebookCodebooksDiseaseParameterGetResponses, GetCodebookCodebooksDiseaseParameterGetErrors, ThrowOnError> => (options.client ?? client).get<GetCodebookCodebooksDiseaseParameterGetResponses, GetCodebookCodebooksDiseaseParameterGetErrors, ThrowOnError>({ url: '/codebooks/{disease}/{parameter}', ...options });

/**
 * Get Step Index
 *
 * Aggregate the per-paper structured index JSONs a coding run produces
 * (data/runs/{id}/step-{n}/index*.index.json) into a single review table.
 */
export const getStepIndexRunsRunIdStepsStepNoIndexGet = <ThrowOnError extends boolean = false>(options: Options<GetStepIndexRunsRunIdStepsStepNoIndexGetData, ThrowOnError>): RequestResult<GetStepIndexRunsRunIdStepsStepNoIndexGetResponses, GetStepIndexRunsRunIdStepsStepNoIndexGetErrors, ThrowOnError> => (options.client ?? client).get<GetStepIndexRunsRunIdStepsStepNoIndexGetResponses, GetStepIndexRunsRunIdStepsStepNoIndexGetErrors, ThrowOnError>({ url: '/runs/{run_id}/steps/{step_no}/index', ...options });

/**
 * Get Stage Prompt
 *
 * Resolve the prompt template a stage uses (read-only), for display +
 * human-in-the-loop supplementation.
 */
export const getStagePromptPromptsStageGet = <ThrowOnError extends boolean = false>(options: Options<GetStagePromptPromptsStageGetData, ThrowOnError>): RequestResult<GetStagePromptPromptsStageGetResponses, GetStagePromptPromptsStageGetErrors, ThrowOnError> => (options.client ?? client).get<GetStagePromptPromptsStageGetResponses, GetStagePromptPromptsStageGetErrors, ThrowOnError>({ url: '/prompts/{stage}', ...options });

/**
 * Read Llm Settings
 */
export const readLlmSettingsSettingsLlmGet = <ThrowOnError extends boolean = false>(options?: Options<ReadLlmSettingsSettingsLlmGetData, ThrowOnError>): RequestResult<ReadLlmSettingsSettingsLlmGetResponses, unknown, ThrowOnError> => (options?.client ?? client).get<ReadLlmSettingsSettingsLlmGetResponses, unknown, ThrowOnError>({ url: '/settings/llm', ...options });

/**
 * Update Llm Settings
 */
export const updateLlmSettingsSettingsLlmPut = <ThrowOnError extends boolean = false>(options: Options<UpdateLlmSettingsSettingsLlmPutData, ThrowOnError>): RequestResult<UpdateLlmSettingsSettingsLlmPutResponses, UpdateLlmSettingsSettingsLlmPutErrors, ThrowOnError> => (options.client ?? client).put<UpdateLlmSettingsSettingsLlmPutResponses, UpdateLlmSettingsSettingsLlmPutErrors, ThrowOnError>({
    url: '/settings/llm',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Health
 */
export const healthHealthGet = <ThrowOnError extends boolean = false>(options?: Options<HealthHealthGetData, ThrowOnError>): RequestResult<HealthHealthGetResponses, unknown, ThrowOnError> => (options?.client ?? client).get<HealthHealthGetResponses, unknown, ThrowOnError>({ url: '/health', ...options });
