// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://127.0.0.1:8000' | (string & {});
};

/**
 * CodebookField
 */
export type CodebookField = {
    /**
     * Name
     */
    name?: string | null;
    /**
     * Label
     */
    label?: string | null;
    /**
     * Type
     */
    type?: string | null;
    /**
     * Required
     */
    required?: boolean;
    /**
     * Prompt
     */
    prompt?: string | null;
};

/**
 * CodebookRead
 */
export type CodebookRead = {
    /**
     * Disease
     */
    disease: string;
    /**
     * Parameter
     */
    parameter: string;
    /**
     * Name
     */
    name?: string | null;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Effect Type
     */
    effect_type?: string | null;
    /**
     * Notes
     */
    notes?: string | null;
    /**
     * Fields
     */
    fields?: Array<CodebookField>;
};

/**
 * CreateRunRequest
 */
export type CreateRunRequest = {
    /**
     * Params
     */
    params?: {
        [key: string]: unknown;
    };
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * LLMProfileRead
 */
export type LlmProfileRead = {
    /**
     * Provider
     */
    provider?: string;
    /**
     * Model
     */
    model?: string;
    /**
     * Api Base
     */
    api_base?: string;
    /**
     * Temperature
     */
    temperature?: string;
    /**
     * Max Tokens
     */
    max_tokens?: string;
    /**
     * Timeout S
     */
    timeout_s?: string;
    /**
     * Verify Ssl
     */
    verify_ssl?: 'default' | 'true' | 'false';
    /**
     * Has Api Key
     */
    has_api_key?: boolean;
    /**
     * Has Module Api Key
     */
    has_module_api_key?: boolean;
    /**
     * Api Key Hint
     */
    api_key_hint?: string;
    /**
     * Resolved Provider
     */
    resolved_provider?: string;
    /**
     * Resolved Model
     */
    resolved_model?: string;
    /**
     * Resolved Api Base
     */
    resolved_api_base?: string;
};

/**
 * LLMProfileUpdate
 */
export type LlmProfileUpdate = {
    /**
     * Provider
     */
    provider?: string | null;
    /**
     * Model
     */
    model?: string | null;
    /**
     * Api Base
     */
    api_base?: string | null;
    /**
     * Api Key
     */
    api_key?: string | null;
    /**
     * Clear Api Key
     */
    clear_api_key?: boolean;
    /**
     * Temperature
     */
    temperature?: string | null;
    /**
     * Max Tokens
     */
    max_tokens?: string | null;
    /**
     * Timeout S
     */
    timeout_s?: string | null;
    /**
     * Verify Ssl
     */
    verify_ssl?: 'default' | 'true' | 'false' | null;
};

/**
 * LLMSettingsRead
 */
export type LlmSettingsRead = {
    /**
     * Profiles
     */
    profiles: {
        [key: string]: LlmProfileRead;
    };
};

/**
 * LLMSettingsUpdate
 */
export type LlmSettingsUpdate = {
    /**
     * Profiles
     */
    profiles?: {
        [key: string]: LlmProfileUpdate;
    };
};

/**
 * RunDetail
 */
export type RunDetail = {
    run: RunRead;
    /**
     * Steps
     */
    steps: Array<StepRead>;
};

/**
 * RunEventRead
 */
export type RunEventRead = {
    /**
     * Id
     */
    id: number;
    /**
     * Run Id
     */
    run_id: string;
    /**
     * Step No
     */
    step_no: number | null;
    /**
     * Ts
     */
    ts: string;
    /**
     * Level
     */
    level: string;
    /**
     * Message
     */
    message: string;
};

/**
 * RunRead
 */
export type RunRead = {
    /**
     * Id
     */
    id: string;
    /**
     * Status
     */
    status: string;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Params
     */
    params: {
        [key: string]: unknown;
    };
};

/**
 * SaveEditedStepRequest
 */
export type SaveEditedStepRequest = {
    /**
     * Rows
     */
    rows?: Array<{
        [key: string]: unknown;
    }> | null;
    /**
     * Columns
     */
    columns?: Array<string> | null;
    /**
     * Data
     */
    data?: {
        [key: string]: unknown;
    } | null;
};

/**
 * StagePromptRead
 */
export type StagePromptRead = {
    /**
     * Stage
     */
    stage: string;
    /**
     * Has Prompt
     */
    has_prompt: boolean;
    /**
     * Source
     */
    source?: string | null;
    /**
     * System
     */
    system?: string | null;
    /**
     * User
     */
    user?: string | null;
    /**
     * Output
     */
    output?: string | null;
};

/**
 * StartStepRequest
 */
export type StartStepRequest = {
    /**
     * Params
     */
    params?: {
        [key: string]: unknown;
    };
};

/**
 * StartStepResponse
 */
export type StartStepResponse = {
    run: RunRead;
    step: StepRead;
};

/**
 * StepJsonRows
 */
export type StepJsonRows = {
    /**
     * Kind
     */
    kind: 'json';
    /**
     * Data
     */
    data: {
        [key: string]: unknown;
    };
};

/**
 * StepRead
 */
export type StepRead = {
    /**
     * Id
     */
    id: number;
    /**
     * Run Id
     */
    run_id: string;
    /**
     * Step No
     */
    step_no: number;
    /**
     * Name
     */
    name: string;
    /**
     * Status
     */
    status: string;
    /**
     * Artifact Path
     */
    artifact_path: string | null;
    /**
     * Edited Artifact Path
     */
    edited_artifact_path: string | null;
    /**
     * Started At
     */
    started_at: string | null;
    /**
     * Finished At
     */
    finished_at: string | null;
};

/**
 * StepTableRows
 */
export type StepTableRows = {
    /**
     * Kind
     */
    kind: 'table';
    /**
     * Columns
     */
    columns: Array<string>;
    /**
     * Rows
     */
    rows: Array<{
        [key: string]: string;
    }>;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

export type ListRunsRunsGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Limit
         */
        limit?: number | null;
        /**
         * Offset
         */
        offset?: number;
    };
    url: '/runs';
};

export type ListRunsRunsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListRunsRunsGetError = ListRunsRunsGetErrors[keyof ListRunsRunsGetErrors];

export type ListRunsRunsGetResponses = {
    /**
     * Response List Runs Runs Get
     *
     * Successful Response
     */
    200: Array<RunRead>;
};

export type ListRunsRunsGetResponse = ListRunsRunsGetResponses[keyof ListRunsRunsGetResponses];

export type CreateRunRunsPostData = {
    body: CreateRunRequest;
    path?: never;
    query?: never;
    url: '/runs';
};

export type CreateRunRunsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateRunRunsPostError = CreateRunRunsPostErrors[keyof CreateRunRunsPostErrors];

export type CreateRunRunsPostResponses = {
    /**
     * Successful Response
     */
    200: RunRead;
};

export type CreateRunRunsPostResponse = CreateRunRunsPostResponses[keyof CreateRunRunsPostResponses];

export type GetRunRunsRunIdGetData = {
    body?: never;
    path: {
        /**
         * Run Id
         */
        run_id: string;
    };
    query?: never;
    url: '/runs/{run_id}';
};

export type GetRunRunsRunIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetRunRunsRunIdGetError = GetRunRunsRunIdGetErrors[keyof GetRunRunsRunIdGetErrors];

export type GetRunRunsRunIdGetResponses = {
    /**
     * Successful Response
     */
    200: RunDetail;
};

export type GetRunRunsRunIdGetResponse = GetRunRunsRunIdGetResponses[keyof GetRunRunsRunIdGetResponses];

export type StartStepRunsRunIdStepsStepNoStartPostData = {
    /**
     * Body
     */
    body?: StartStepRequest | null;
    path: {
        /**
         * Run Id
         */
        run_id: string;
        /**
         * Step No
         */
        step_no: number;
    };
    query?: never;
    url: '/runs/{run_id}/steps/{step_no}/start';
};

export type StartStepRunsRunIdStepsStepNoStartPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type StartStepRunsRunIdStepsStepNoStartPostError = StartStepRunsRunIdStepsStepNoStartPostErrors[keyof StartStepRunsRunIdStepsStepNoStartPostErrors];

export type StartStepRunsRunIdStepsStepNoStartPostResponses = {
    /**
     * Successful Response
     */
    200: StartStepResponse;
};

export type StartStepRunsRunIdStepsStepNoStartPostResponse = StartStepRunsRunIdStepsStepNoStartPostResponses[keyof StartStepRunsRunIdStepsStepNoStartPostResponses];

export type DownloadStepArtifactRunsRunIdStepsStepNoArtifactGetData = {
    body?: never;
    path: {
        /**
         * Run Id
         */
        run_id: string;
        /**
         * Step No
         */
        step_no: number;
    };
    query?: never;
    url: '/runs/{run_id}/steps/{step_no}/artifact';
};

export type DownloadStepArtifactRunsRunIdStepsStepNoArtifactGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DownloadStepArtifactRunsRunIdStepsStepNoArtifactGetError = DownloadStepArtifactRunsRunIdStepsStepNoArtifactGetErrors[keyof DownloadStepArtifactRunsRunIdStepsStepNoArtifactGetErrors];

export type DownloadStepArtifactRunsRunIdStepsStepNoArtifactGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetStepRowsRunsRunIdStepsStepNoRowsGetData = {
    body?: never;
    path: {
        /**
         * Run Id
         */
        run_id: string;
        /**
         * Step No
         */
        step_no: number;
    };
    query?: {
        /**
         * Name
         */
        name?: string | null;
    };
    url: '/runs/{run_id}/steps/{step_no}/rows';
};

export type GetStepRowsRunsRunIdStepsStepNoRowsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetStepRowsRunsRunIdStepsStepNoRowsGetError = GetStepRowsRunsRunIdStepsStepNoRowsGetErrors[keyof GetStepRowsRunsRunIdStepsStepNoRowsGetErrors];

export type GetStepRowsRunsRunIdStepsStepNoRowsGetResponses = {
    /**
     * Response Get Step Rows Runs  Run Id  Steps  Step No  Rows Get
     *
     * Successful Response
     */
    200: StepTableRows | StepJsonRows;
};

export type GetStepRowsRunsRunIdStepsStepNoRowsGetResponse = GetStepRowsRunsRunIdStepsStepNoRowsGetResponses[keyof GetStepRowsRunsRunIdStepsStepNoRowsGetResponses];

export type SaveEditedStepRunsRunIdStepsStepNoEditedPutData = {
    body: SaveEditedStepRequest;
    path: {
        /**
         * Run Id
         */
        run_id: string;
        /**
         * Step No
         */
        step_no: number;
    };
    query?: never;
    url: '/runs/{run_id}/steps/{step_no}/edited';
};

export type SaveEditedStepRunsRunIdStepsStepNoEditedPutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SaveEditedStepRunsRunIdStepsStepNoEditedPutError = SaveEditedStepRunsRunIdStepsStepNoEditedPutErrors[keyof SaveEditedStepRunsRunIdStepsStepNoEditedPutErrors];

export type SaveEditedStepRunsRunIdStepsStepNoEditedPutResponses = {
    /**
     * Successful Response
     */
    200: StepRead;
};

export type SaveEditedStepRunsRunIdStepsStepNoEditedPutResponse = SaveEditedStepRunsRunIdStepsStepNoEditedPutResponses[keyof SaveEditedStepRunsRunIdStepsStepNoEditedPutResponses];

export type StreamEventsRunsRunIdEventsGetData = {
    body?: never;
    path: {
        /**
         * Run Id
         */
        run_id: string;
    };
    query?: never;
    url: '/runs/{run_id}/events';
};

export type StreamEventsRunsRunIdEventsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type StreamEventsRunsRunIdEventsGetError = StreamEventsRunsRunIdEventsGetErrors[keyof StreamEventsRunsRunIdEventsGetErrors];

export type StreamEventsRunsRunIdEventsGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ListRunEventsRunsRunIdEventsHistoryGetData = {
    body?: never;
    path: {
        /**
         * Run Id
         */
        run_id: string;
    };
    query?: {
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/runs/{run_id}/events/history';
};

export type ListRunEventsRunsRunIdEventsHistoryGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListRunEventsRunsRunIdEventsHistoryGetError = ListRunEventsRunsRunIdEventsHistoryGetErrors[keyof ListRunEventsRunsRunIdEventsHistoryGetErrors];

export type ListRunEventsRunsRunIdEventsHistoryGetResponses = {
    /**
     * Response List Run Events Runs  Run Id  Events History Get
     *
     * Successful Response
     */
    200: Array<RunEventRead>;
};

export type ListRunEventsRunsRunIdEventsHistoryGetResponse = ListRunEventsRunsRunIdEventsHistoryGetResponses[keyof ListRunEventsRunsRunIdEventsHistoryGetResponses];

export type GetCodebookCodebooksDiseaseParameterGetData = {
    body?: never;
    path: {
        /**
         * Disease
         */
        disease: string;
        /**
         * Parameter
         */
        parameter: string;
    };
    query?: never;
    url: '/codebooks/{disease}/{parameter}';
};

export type GetCodebookCodebooksDiseaseParameterGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetCodebookCodebooksDiseaseParameterGetError = GetCodebookCodebooksDiseaseParameterGetErrors[keyof GetCodebookCodebooksDiseaseParameterGetErrors];

export type GetCodebookCodebooksDiseaseParameterGetResponses = {
    /**
     * Successful Response
     */
    200: CodebookRead;
};

export type GetCodebookCodebooksDiseaseParameterGetResponse = GetCodebookCodebooksDiseaseParameterGetResponses[keyof GetCodebookCodebooksDiseaseParameterGetResponses];

export type GetStepIndexRunsRunIdStepsStepNoIndexGetData = {
    body?: never;
    path: {
        /**
         * Run Id
         */
        run_id: string;
        /**
         * Step No
         */
        step_no: number;
    };
    query?: never;
    url: '/runs/{run_id}/steps/{step_no}/index';
};

export type GetStepIndexRunsRunIdStepsStepNoIndexGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetStepIndexRunsRunIdStepsStepNoIndexGetError = GetStepIndexRunsRunIdStepsStepNoIndexGetErrors[keyof GetStepIndexRunsRunIdStepsStepNoIndexGetErrors];

export type GetStepIndexRunsRunIdStepsStepNoIndexGetResponses = {
    /**
     * Successful Response
     */
    200: StepTableRows;
};

export type GetStepIndexRunsRunIdStepsStepNoIndexGetResponse = GetStepIndexRunsRunIdStepsStepNoIndexGetResponses[keyof GetStepIndexRunsRunIdStepsStepNoIndexGetResponses];

export type GetStagePromptPromptsStageGetData = {
    body?: never;
    path: {
        /**
         * Stage
         */
        stage: string;
    };
    query?: {
        /**
         * Disease
         */
        disease?: string | null;
        /**
         * Parameter
         */
        parameter?: string | null;
        /**
         * Strategy
         */
        strategy?: string | null;
    };
    url: '/prompts/{stage}';
};

export type GetStagePromptPromptsStageGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetStagePromptPromptsStageGetError = GetStagePromptPromptsStageGetErrors[keyof GetStagePromptPromptsStageGetErrors];

export type GetStagePromptPromptsStageGetResponses = {
    /**
     * Successful Response
     */
    200: StagePromptRead;
};

export type GetStagePromptPromptsStageGetResponse = GetStagePromptPromptsStageGetResponses[keyof GetStagePromptPromptsStageGetResponses];

export type ReadLlmSettingsSettingsLlmGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/settings/llm';
};

export type ReadLlmSettingsSettingsLlmGetResponses = {
    /**
     * Successful Response
     */
    200: LlmSettingsRead;
};

export type ReadLlmSettingsSettingsLlmGetResponse = ReadLlmSettingsSettingsLlmGetResponses[keyof ReadLlmSettingsSettingsLlmGetResponses];

export type UpdateLlmSettingsSettingsLlmPutData = {
    body: LlmSettingsUpdate;
    path?: never;
    query?: never;
    url: '/settings/llm';
};

export type UpdateLlmSettingsSettingsLlmPutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateLlmSettingsSettingsLlmPutError = UpdateLlmSettingsSettingsLlmPutErrors[keyof UpdateLlmSettingsSettingsLlmPutErrors];

export type UpdateLlmSettingsSettingsLlmPutResponses = {
    /**
     * Successful Response
     */
    200: LlmSettingsRead;
};

export type UpdateLlmSettingsSettingsLlmPutResponse = UpdateLlmSettingsSettingsLlmPutResponses[keyof UpdateLlmSettingsSettingsLlmPutResponses];

export type HealthHealthGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health';
};

export type HealthHealthGetResponses = {
    /**
     * Response Health Health Get
     *
     * Successful Response
     */
    200: {
        [key: string]: string;
    };
};

export type HealthHealthGetResponse = HealthHealthGetResponses[keyof HealthHealthGetResponses];
